apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: exoskeleton-db
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: exoskeleton-db
    spec:
      containers:
      - name: exoskeleton-db
        image: lynxaegon/hivecluster:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 10
        ports:
        - containerPort: 80
#        volumeMounts:
#        - name: config
#          mountPath: "/app/config"
        env:
        - name: HIVE_CONFIG
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app']
        - name: HIVE_POD_APP
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app']
        - name: HIVE_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: HIVE_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
#      volumes:
#      - name: config
#        configMap:
#          name: "hivenode-frontend-config"
