apiVersion: v1
kind: Service
metadata:
  name: exoskeleton-frontend
  labels:
    app: exoskeleton-frontend
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: ws
    port: 8080
    targetPort: 8080
  selector:
    app: exoskeleton-frontend
