apiVersion: v1
kind: Service
metadata:
  name: exoskeleton-frontend
  labels:
    app: exoskeleton-frontend
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: exoskeleton-frontend
