name: Build & Deploy
on:
  push:
    branches: 
      - release

jobs:
  runner:
    name: Runner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - uses: actions/checkout@master
        with:
          ref: refs/heads/master
      - uses: ./.github/actions/build-action
        env:
          DO_KUBE_CLUSTER: ${{ secrets.DO_KUBE_CLUSTER }}
          DO_API_KEY: ${{ secrets.DO_API_KEY }}
