name: Build & Deploy
on: [push]

jobs:
  build_and_deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: refs/heads/master
      - uses: ./.github/actions/build-action
        env:
          DO_KUBE_CLUSTER: ${{ secrets.DO_KUBE_CLUSTER }}
          DO_API_KEY: ${{ secrets.DO_API_KEY }}
