name: Build & Deploy
on: [push]

jobs:
  build_and_deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: refs/heads/master
      - uses: ./.github/actions/build-action
        env:
          KUBE_CERTS_DOWNLOADER: ${{ secrets.KUBE_CERTS_DOWNLOADER }}
